networks:
  eclipse_net:
    driver : bridge

volumes:
  database_data:
  static_data:
  media_data:
  kafka_data:

services:
  db:
    image: mysql
    container_name: eclipse_database
    environment:
      MYSQL_DATABASE: eclipse
      MYSQL_USER: eclipse_user
      MYSQL_ROOT_PASSWORD : ${DATABASE_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD : 0
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
     - eclipse_net
    volumes:
      - database_data:/var/lib/mysql
      - ./compose/mysql/permissions/:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  api:
    build:
      context: .
      dockerfile: ./compose/django/dockerfile
    container_name: eclipse_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
     - eclipse_net
    env_file:
      - ./.env
    volumes:
      - static_data:/usr/src/app/static/
      - media_data:/usr/src/app/media/

  nginx:
    image: nginx:latest
    container_name: eclipse_nginx
    networks:
     - eclipse_net
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/staticfiles/
      - media_data:/mediafiles/
    depends_on:
      - api

  redis :
    image: redis:latest
    container_name: eclipse_redis
    ports :
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - eclipse_net
    env_file:
      - ./.env

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    restart: always
    container_name: eclipse_zookeeper
    networks:
      - eclipse_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    networks:
      - eclipse_net
    container_name: eclipse_kafka
    restart :  on-failure
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: eclipse_kafka_ui
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - eclipse_net
