networks:
  eclipse_net:
    driver : bridge

volumes:
  database_data:
  static_data:
  media_data:

services:
  db:
    image: mysql
    container_name: eclipse_database
    environment:
      MYSQL_DATABASE: eclipse
      MYSQL_USER: eclipse_user
      MYSQL_ROOT_PASSWORD : ${MYSQL_ECLIPSE_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD : 0
      MYSQL_PASSWORD: ${MYSQL_ECLIPSE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
     - eclipse_net
    volumes:
      - database_data:/var/lib/mysql
    
  api:
    build: 
      context: .
      dockerfile: ./compose/django/dockerfile
    container_name: eclipse_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
     - eclipse_net
    env_file:
      - ./.env
    volumes:
      - static_data:/usr/src/app/static/
      - media_data:/usr/src/app/media/

  nginx:
    image: nginx:latest
    container_name: eclipse_nginx
    networks:
     - eclipse_net
    ports:
      - "80:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/staticfiles/
      - media_data:/mediafiles/
    depends_on:
      - api
    
  redis : 
    image: redis:latest
    container_name: eclipse_redis
    ports :
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - eclipse_net
    depends_on:
      - api